### ISSUE TITLE
The app crashes when opening some folders in grid view

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#799]
The app doesn't crash when opening some folders, if the folder is empty or if it's pinned to the sidebar and you open it from there.

**after opening a folder, the first folder inside has an animation as if you had selected it, as seen in the gif**

**v0.8.1**
![crash](https://user-images.githubusercontent.com/61259627/82213234-d497c080-98e1-11ea-8f7c-e024891813d5.gif)

**Comment by yaichenbaum** [comment]
This issue has been fixed with #812 and will roll out in the next update to Files UWP.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.

**Comment by xPoppyx** [comment]
still happening in the latest version
![bug](https://user-images.githubusercontent.com/61259627/83682991-adfca980-a5b2-11ea-8959-c569257b61a4.gif)

**Comment by Richard-HM** [comment]
@yaichenbaum can you reopen? in grid view, the app still crashing when opening some folders (v0.9.2)

**Comment by yaichenbaum** [comment]
Are there any things in common with the folders that crash?

**Comment by Richard-HM** [comment]
I thought that maybe the crashing was caused by some specific file type, but, it crashes even opening one that contains another simple folder inside

**Comment by Richard-HM** [comment]
![crash](https://user-images.githubusercontent.com/61259627/84098822-3a093980-a9d6-11ea-92e2-2f87bc50618a.gif)

**Comment by Richard-HM** [comment]
I'm not sure if it was after some changes to the selection system made a few days before May 18

**Comment by yaichenbaum** [comment]
Is this still an issue in v0.10.2?

**Comment by XPoppyX** [comment]
works fine now

**Comment by XPoppyX** [comment]
somehow it starts crashing again.

but everything works fine if I run it from VS, then when reopening the app normally is when it crashes opening folders.

This time I noticed something, and is that when you open the app normally, opening folders, the first item inside makes this weird animation:

**result: crash**

![crash](https://user-images.githubusercontent.com/61259627/84842451-2764b500-b013-11ea-9a71-27d1b528ecd4.gif)

---------------------------------------------------------------

however when I run the app from VS, when opening folder that doesn't happen:

**result: works fine, no crashing**
![animation](https://user-images.githubusercontent.com/61259627/84842514-5844ea00-b013-11ea-827d-37adea23d431.gif)

**Comment by duke7553** [comment]
@XPoppyX If this is still an issue, can you please upload your debug logs?

**Comment by XPoppyX** [comment]
for now it no longer crashes after it no longer does the weird animation I mentioned before when opening a folder
